# picom: A compositor for X11
# --------------------------------------
# Documentation for picom configuration:
# https://picom.app/

### PICOM CONFIGURATION ###

# SHADOWS
shadow = true;
shadow-radius = 11;
shadow-opacity = 0.30;
shadow-offset-x = -2;
shadow-offset-y = -3;

# CORNERS
corner-radius = 10;

# BLUR
blur-method = "dual_kawase";
blur-strength = 2;
blur-background = true;

# GENERAL SETTINGS
backend = "glx";
vsync = true;
# dithered-present = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-client-leader = true;
detect-transient = true;
use-ewmh-active-win = true;
use-damage = true;
xrender-sync-fence = true
log-level = "warn";

# BASIC ANIMATIONS
animations = (
  {
    triggers = [ "open" ];
    preset = "appear";
    scale = 0.8;
    duration = 0.2;
  },
  {
    triggers = [ "close" ];
    preset = "disappear";
    scale = 0.8;
    duration = 0.2;
  },
  {
    triggers = [ "geometry" ];
    preset = "geometry-change";
    scale = 0.2;
  },
)
@include "rules.conf"
