# Rule-based per-window options.
# See `https://picom.app/#_window_rules` for options.

rules: (
  {
    match = "class_i = 'dwm'";
    corner-radius = 0;
  },
  {
    match = "focused";
    opacity = 0.98;
    blur-background = true;
    shadow = true;
  },
  {
    match = "!focused";
    opacity = 0.90;
    blur-background = false;
    shadow = false;
  },
  {
    match = "fullscreen";
    corner-radius = 0;
  },
  {
    match = "window_type = 'tooltip'";
    fade = true;
    shadow = true;
    opacity = 0.8;
    focus = true;
    full-shadow = false;
  },
  {
    match = "window_type = 'popup_menu'";
    opacity = 0.9;
  },
  {
    match = "window_type = 'dropdown_menu'";
    opacity = 0.9;
  },
)
